### ISSUE TITLE
remove extraneous files

### ISSUE THREAD

**Issue by beanumber** [RandiLGarcia/dyadr#24]
@CarolLiuSifan can you please remove the files `.RData` and `alliance.RData`? They don't belong in the root directory of the package.

**Comment by beanumber** [comment]
@CarolLiuSifan can you also please add yourself as a `ctb` in `DESCRIPTION` (if @RandiLGarcia is willing)?

**Comment by beanumber** [comment]
Also, @CarolLiuSifan on line 31 of `alliance-data.R` you want `\url{}` instead of `\href{}`.

**Comment by CarolLiuSifan** [comment]
But Alliance is the added dataset, if I removed it will my dataset still be there?

**Comment by CarolLiuSifan** [comment]
ok, I'll fix the rest.

**Comment by beanumber** [comment]
`data/alliance.rda` is the data file that you added (correctly). `alliance.RData` is at the root level of the repository, where it cannot be. 

What is the difference between the two files? If there is some wrangling that takes `alliance.RData` and transforms it into `data/alliance.rda`, then that code should go in `data-raw/`. If there is no such wrangling and the files are the same, then simply delete `alliance.RData`.

**Comment by CarolLiuSifan** [comment]
Ok, I see. Thanks, I fixed everything and submitted a new pull request.
